// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mebkikuipavdlvkbfull.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1lYmtpa3VpcGF2ZGx2a2JmdWxsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjE1ODQyNjIsImV4cCI6MjA3NzE2MDI2Mn0.zqXIFo2L7O3kwvF53L28lMqgMJV0OrxdxuVSnBOD13k";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});